workspace 'Runner.xcworkspace'

# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network requests to Google Analytics when you run `pod install`.
# To disable this behavior, add `ENV['COCOAPODS_DISABLE_STATS'] = 'true'` to your Podfile.
#
# For more information, see: https://guides.cocoapods.org/syntax/podfile.html#stats

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'go_engine', :path => '../../GOModules'

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end
end